Update git_push.yml

diff --git a/roles/axp/common/tasks/git_push.yml b/roles/axp/common/tasks/git_push.yml
--- a/roles/axp/common/tasks/git_push.yml
+++ b/roles/axp/common/tasks/git_push.yml
@@ -59,10 +59,14 @@
       resp=$(git push --force -u up ORIG_HEAD:refs/heads/upstream_{{ android_shortversion }} >> /dev/null 2&>1)
       rerr=$?
       if [ $rerr -ne 0 ]; then
-          tail -n 20 "$resp" | grep -q "pack exceeds maximum allowed size"
-          || max=$(git log --oneline|wc -l); for i in $(seq  $max -60000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
-          || max=$(git log --oneline|wc -l); for i in $(seq  $max -10000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
-          || max=$(git log --oneline|wc -l); for i in $(seq  $max -1000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done
+          echo "[GIT] error $rerr occured while pushing." >> {{ BUILD_LOG }}
+          tail -n 20 "$resp" | grep -q "pack exceeds maximum allowed size" || err=$rerr
+          if [ $? -eq 0 ]; then
+              echo "[GIT] pack size too big, pushing in chunks now.." >> {{ BUILD_LOG }}
+              max=$(git log --oneline|wc -l); for i in $(seq  $max -60000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
+              || max=$(git log --oneline|wc -l); for i in $(seq  $max -10000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
+              || max=$(git log --oneline|wc -l); for i in $(seq  $max -1000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done
+          fi
       fi
       echo "[GIT] pushed/updated upstream_{{ android_shortversion }}" >> {{ BUILD_LOG }}
 
