Update git_push.yml

diff --git a/roles/axp/common/tasks/git_push.yml b/roles/axp/common/tasks/git_push.yml
--- a/roles/axp/common/tasks/git_push.yml
+++ b/roles/axp/common/tasks/git_push.yml
@@ -60,22 +60,31 @@
       git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }} >> /dev/null 2>&1 || rerr=$?
       if [ $rerr -ne 0 ]; then
           resp=$(git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }} >> /dev/null 2>&1 || true)
-          echo "$resp" | tail -n 20 | grep -q "pack exceeds maximum allowed size" || err=$rerr
-          if [ $? -eq 0 ]; then
+          found=0
+          echo "$resp" | tail -n 20 | grep -q "pack exceeds maximum allowed size" || found=1
+          if [ $found -eq 0 ]; then
               echo "[GIT] pack size too big for $reponame, pushing in chunks now.." >> {{ BUILD_LOG }}
-              max=$(git log --oneline|wc -l); for i in $(seq  $max -60000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
-              || (echo "[GIT] reducing chunk size to: 10000" >> {{ BUILD_LOG }} ; max=$(git log --oneline|wc -l); for i in $(seq  $max -10000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done) \
-              || (echo "[GIT] reducing chunk size even more to: 1000"  >> {{ BUILD_LOG }}; max=$(git log --oneline|wc -l); for i in $(seq  $max -1000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done)
+              max=$(git log --oneline|wc -l); for i in $(seq  $max -60000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1; done \
+              || (echo "[GIT] reducing chunk size to: 10000" >> {{ BUILD_LOG }} ; max=$(git log --oneline|wc -l); for i in $(seq  $max -10000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1; done) \
+              || (echo "[GIT] reducing chunk size even more to: 1000"  >> {{ BUILD_LOG }}; max=$(git log --oneline|wc -l); for i in $(seq  $max -1000 1); do echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1; done)
               if [ $? -ne 0 ];then
                   echo "$resp" | tail -n 20 >> {{ BUILD_LOG }}
                   exit 3
               fi
-              # now the previous push should just work
+              # now the final push should just work
               git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }}
           else
-             echo "[GIT] error $rerr occured while pushing" >> {{ BUILD_LOG }}
-             exit $rerr
-             #git push --force -u up FETCH_HEAD:refs/heads/upstream_{{ android_shortversion }} >> /dev/null 2>&1
+             found=0
+             echo "$resp" | tail -n 20 | grep -q "fatal: did not receive expected object" || found=1
+             if [ $found -eq 0 ]; then
+               obj=$(echo "$resp" | tail -n 20 | grep -o "fatal: did not receive expected object .*" | cut -d ' ' -f 7)
+               git push --force -u up ${obj}:refs/heads/upstream_{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1
+               git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1
+             else
+               echo "[GIT] error $rerr occured while pushing" >> {{ BUILD_LOG }}
+               echo "$resp" | tail -n 20 >> {{ BUILD_LOG }}
+               exit $rerr
+             fi
           fi
       fi
       echo "[GIT] pushed/updated upstream_{{ android_shortversion }}" >> {{ BUILD_LOG }}
