**refactor(roles/axp/common/tasks):- add wireguard patching and kernel defconfig handling
- replaced file creation with shell script for wireguard patching
- added conditional checks to handle different kernel paths and vendor-specific logic
- updated kernel defconfig handling to set global and device-specific settings

diff --git a/roles/axp/common/tasks/patch.yml b/roles/axp/common/tasks/patch.yml
--- a/roles/axp/common/tasks/patch.yml
+++ b/roles/axp/common/tasks/patch.yml
@@ -11,11 +11,37 @@
 - name: "Prepare kernel patchers"
   include_tasks: prep_kernel_patchers.yml
   
-- name: "Disable wireguard handling by vendor/axp"
-  ansible.builtin.file:
-    path: "{{ SRCPATH }}/{{ target_kernel_dir }}/.wg.patched"
-    state: touch
-  when: skip_wireguard is defined and skip_wireguard | bool
+- name: "Apply Wireguard patch"
+  ansible.builtin.shell: |
+      # patch kernel source to build wireguard module
+      # (see: https://www.wireguard.com/compilation/#building-directly-in-tree)
+
+      CPWD="{{ SRCPATH }}"
+
+      {% if git_pixel_kernel_manifest_branch is defined and target_model_vendor == "Google" %}
+      AXP_KERNEL_PATH="{{ git_pixel_kernel_source }}"
+      {% else %}
+      AXP_KERNEL_PATH="{{ target_kernel_dir }}"
+      {% endif %}
+      
+      if [ ! -f "$AXP_KERNEL_PATH/.wg.patched" ];then
+          cd $AXP_KERNEL_PATH
+          if [ -d "net/wireguard" ];then rm -rf net/wireguard ;fi
+          mkdir -p net/wireguard/compat
+          if [ -f $CPWD/kernel/wireguard-linux-compat/kernel-tree-scripts/create-patch.sh ];then
+              $CPWD/kernel/wireguard-linux-compat/kernel-tree-scripts/create-patch.sh | patch -p1 --no-backup-if-mismatch
+              git add -A && git commit --author="Jason A. Donenfeld <Jason@zx2c4.com>" -m "apply wireguard-linux-compat"
+              echo "[AXP] .. patched kernel sources for wireguard"
+          else
+              echo "[AXP] ERROR patching kernel sources for wireguard (missing compat patcher)!"
+              exit 3
+          fi
+          cd $CPWD
+          touch $AXP_KERNEL_PATH/.wg.patched
+      else
+          echo "[AXP] .. kernel is already patched for wireguard (patch indicator exists)"
+      fi
+  when: skip_wireguard is undefined or not skip_wireguard | bool
 
 - name: "Apply AXP.OS patches (common, >= A15)"
   ansible.builtin.shell: |
@@ -89,7 +115,15 @@
 - name: "Apply AXP.OS adjustments"
   ansible.builtin.shell: |
     {{ DOS_INIT }}
-    
+
+    CPWD="{{ SRCPATH }}"
+
+    {% if git_pixel_kernel_manifest_branch is defined and target_model_vendor == "Google" %}
+    export AXP_KERNEL_PATH="{{ git_pixel_kernel_source }}"
+    {% else %}
+    export AXP_KERNEL_PATH="{{ target_kernel_dir }}"
+    {% endif %}
+
     {% if sub_model is defined %}
     lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
     {% else %}
@@ -99,8 +133,35 @@
     export AXP_DEVICE="{{ common_target_model | d(target_model) }}"
     export AXP_DEVICEVENDOR="{{ target_model_vendor | lower }}"
     export AXP_LOW_STORAGE="{{ remove_space_reservation | d('no') }}"
+    export AXP_TARGET_VERSION={{ android_version_int }}
+
+    # get build vars (requires a lunch before!)
+    export AXP_TARGET_ARCH=$(build/soong/soong_ui.bash --dumpvar-mode TARGET_ARCH  2>/dev/null)
+    export AXP_KERNEL_CONF=$(build/soong/soong_ui.bash --dumpvar-mode TARGET_KERNEL_CONFIG  2>/dev/null)
     
+    # FIXME: legacy handling, should be merged here
     vendor/axp/axp.sh >> {{ BUILD_LOG }} 2>&1
+
+    # patch kernel defconfig
+    if [ ! -f "$AXP_KERNEL_PATH/.defconf.patched" ];then
+        for cf in $AXP_DEFCONFIG_GLOBALS; do
+          grep -q "^$cf=y" $AXP_KERNEL_PATH/arch/$AXP_TARGET_ARCH/configs/$AXP_KERNEL_CONF || echo -e "\n$cf=y" >> $AXP_KERNEL_PATH/arch/$AXP_TARGET_ARCH/configs/$AXP_KERNEL_CONF
+          cd $AXP_KERNEL_PATH
+          git add -A && git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "defconfig: applied: $cf"
+          echo "[AXP] .. kernel globals defconfig $cf has been set"
+          cd $CPWD
+        done
+        for cfd in $AXP_DEFCONFIG_DEVICE; do
+          grep -q "^$cfd" $AXP_KERNEL_PATH/arch/$AXP_TARGET_ARCH/configs/$AXP_KERNEL_CONF || echo -e "\n$cfd" >> $AXP_KERNEL_PATH/arch/$AXP_TARGET_ARCH/configs/$AXP_KERNEL_CONF
+          cd $AXP_KERNEL_PATH
+          git add -A && git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "defconfig: applied $cfd"
+          echo "[AXP] .. kernel device specific defconfig $cfd has been set"
+          cd $CPWD
+        done
+        touch $AXP_KERNEL_PATH/.defconf.patched
+    else
+        echo "[AXP] .. kernel defconfig is already patched (patch indicator exists)"
+    fi
   args:
     executable: /bin/bash
     chdir: "{{ SRCPATH }}"
