Update build.sh.j2

diff --git a/roles/graphene/bluejay/templates/build.sh.j2 b/roles/graphene/bluejay/templates/build.sh.j2
--- a/roles/graphene/bluejay/templates/build.sh.j2
+++ b/roles/graphene/bluejay/templates/build.sh.j2
@@ -107,11 +107,19 @@ fi
 if [ ! -z "{{ release_channel }}" -a "{{ release_channel }}" == "skip" ];then
     echo ".. skipping release as requested ({{ release_channel }})"
 else
-    scp releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-ota_update-${GBUILDID}.zip \
-        releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-factory-${GBUILDID}.zip \
-        releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-{{ release_channel }} \
-        $DELTABUILD \
-        {{ custom_release_server }}:{{ custom_release_server_path }}
+    # the cloud VM has issues to response sometimes so lets loop
+    # several times in the hope this get fixed
+    TRY=1
+    while [ $TRY -le 3 ];do
+        echo "trying to upload to {{ custom_release_server }} ... (try $TRY of 3)"
+        timeout 5m scp releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-ota_update-${GBUILDID}.zip \
+            releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-factory-${GBUILDID}.zip \
+            releases/${GBUILDID}/release-{{ target_model }}-${GBUILDID}/{{ target_model }}-{{ release_channel }} \
+            $DELTABUILD \
+            {{ custom_release_server }}:{{ custom_release_server_path }} && TRY=999
+         TRY=$(( TRY + 1 ))
+    done
+    [ $TRY -ne 1000 ] && echo "Error while uploading update to {{ custom_release_server }}" && exit 3
 
     # cleanup prev delta build
     if [ ! -z "$DELTABUILD" ] && [ -d "releases/${PREV_GBUILDID}" ] && [ "{{ post_cleanup }}" == "true" ] ;then
