Update build.sh.j2

diff --git a/roles/eos/g4/templates/build.sh.j2 b/roles/eos/g4/templates/build.sh.j2
--- a/roles/eos/g4/templates/build.sh.j2
+++ b/roles/eos/g4/templates/build.sh.j2
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# be strict on failures
+set -e
+
 # set required vars
 export EOS_RELEASE_TYPE={{ EOS_RELEASE_TYPE }}
 export JKZIPDIR="{{ JKZIPDIR }}"
