axp: init: test web

diff --git a/roles/axp/common_init_device/tasks/setup_website.yml b/roles/axp/common_init_device/tasks/setup_website.yml
--- a/roles/axp/common_init_device/tasks/setup_website.yml
+++ b/roles/axp/common_init_device/tasks/setup_website.yml
@@ -41,34 +41,40 @@
 
 - name: "Setup website: add & push changes"
   ansible.builtin.shell: |
-      echo "[GIT][WEBSITE] starting git commit process" >> {{ BUILD_LOG }}
-      source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}
+    cat "{{ init_device_temp_path }}/params/device_{{ sub_model | d(target_model) }}.params"
+    exit 4
 
-      if [ "{{ git_axpos_website_workflow_force }}" = true ] && [ -f content/devices/{{ target_model_vendor }}/{{ target_model }}.md ] ;then
-        rm -v content/devices/{{ target_model_vendor }}/{{ target_model }}.md
-      fi
+    echo "[GIT][WEBSITE] starting git commit process" >> {{ BUILD_LOG }}
+    source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}
 
-      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
-      if [ $CMTL -gt 0 ];then
-          git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
-          git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "axp: {{ sub_model | d(target_model) }}: added/updated vars" >> {{ BUILD_LOG }} 2>&1
-          echo "[GIT][WEBSITE] git commit done" >> {{ BUILD_LOG }}
+    if [ "{{ git_axpos_website_workflow_force }}" = true ] && [ -f content/devices/{{ target_model_vendor }}/{{ target_model }}.md ] ;then
+    rm -v content/devices/{{ target_model_vendor }}/{{ target_model }}.md
+    fi
 
-          CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
-          REMHASH=$(git log --pretty=oneline --decorate | grep "origin/{{ init_device_website_branch }}" |cut -d ' ' -f1)
-            
-          if [ "$CURHASH" != "$REMHASH" ]; then
-              echo "[GIT][WEBSITE] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
-              git push origin {{ init_device_website_branch }} >> {{ BUILD_LOG }} 2>&1
-          else
-              echo "[GIT][WEBSITE] pushing skipped ($CURHASH == $REMHASH)!" >> {{ BUILD_LOG }}
-          fi
-      else
-          echo "[GIT][WEBSITE] git commit skipped (no changes)" >> {{ BUILD_LOG }}
-      fi
+    CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
+    if [ $CMTL -gt 0 ];then
+        git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
+        git commit {{ git_commit_args | d('') }} \
+            --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" \
+            -m "axp: {{ sub_model | d(target_model) }}: added/updated vars" \
+            >> {{ BUILD_LOG }} 2>&1
+        echo "[GIT][WEBSITE] git commit done" >> {{ BUILD_LOG }}
+
+        CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
+        REMHASH=$(git log --pretty=oneline --decorate | grep "origin/{{ init_device_website_branch }}" |cut -d ' ' -f1)
+
+        if [ "$CURHASH" != "$REMHASH" ]; then
+            echo "[GIT][WEBSITE] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
+            git push origin {{ init_device_website_branch }} >> {{ BUILD_LOG }} 2>&1
+        else
+            echo "[GIT][WEBSITE] pushing skipped ($CURHASH == $REMHASH)!" >> {{ BUILD_LOG }}
+        fi
+    else
+        echo "[GIT][WEBSITE] git commit skipped (no changes)" >> {{ BUILD_LOG }}
+    fi
   args:
-      chdir: "{{ init_device_temp_path }}"
-      executable: /bin/bash
+    chdir: "{{ init_device_temp_path }}"
+    executable: /bin/bash
   when: info_added.changed or id_pro_added.changed or id_slim_added.changed or git_axpos_website_workflow_force | bool
 
 # - name: "Setup website: run force generate page action"
@@ -94,6 +100,5 @@
 
 - name: "Setup website: End clean"
   ansible.builtin.file:
-      path: "{{ init_device_temp_path }}"
-      state: absent
-
+    path: "{{ init_device_temp_path }}"
+    state: absent
