Refactor kernel directory handling with error check
Updated KERN_REL_DIR retrieval and added error handling for directory existence.

diff --git a/roles/axp/common/defaults/main.yml b/roles/axp/common/defaults/main.yml
--- a/roles/axp/common/defaults/main.yml
+++ b/roles/axp/common/defaults/main.yml
@@ -424,8 +424,14 @@ SH_COMMON_BUILD_SNIPPET: |
     ###### BUILD GOOGLE PIXEL KERNEL
     cd {{ git_pixel_kernel_dir }}
     {{ pixel_kernel_buildcmd }} >> {{ BUILD_LOG }} 2>&1
-    KERN_REL_DIR=$(grep string_value {{ SRCPATH }}/build/release/flag_values/{{ android_target_release }}/RELEASE_KERNEL_{{ target_model }}_DIR.textproto | cut -d '"' -f2 | tr -d " " | tail -n1)
-    cp -av {{ pixel_kernel_buildout }}/* $KERN_REL_DIR/ >> {{ BUILD_LOG }} 2>&1
+    KERN_REL_DIR=$(grep string_value {{ SRCPATH }}/build/release/flag_values/{{ android_target_release }}/RELEASE_KERNEL_{{ target_model | upper() }}_DIR.textproto | cut -d '"' -f2 | tr -d " " | tail -n1)
+    echo "KERN_REL_DIR: >$KERN_REL_DIR<"
+    if [ -d "$KERN_REL_DIR" ];then
+        cp -av {{ pixel_kernel_buildout }}/* $KERN_REL_DIR/ >> {{ BUILD_LOG }} 2>&1
+    else
+        echo "ERROR: KERN_REL_DIR DOES NOT EXIST!"
+        exit 33
+    else
     cd {{ SRCPATH }}
     {% endif %}
 
