Update main.yml

diff --git a/roles/axp/common/defaults/main.yml b/roles/axp/common/defaults/main.yml
--- a/roles/axp/common/defaults/main.yml
+++ b/roles/axp/common/defaults/main.yml
@@ -308,76 +308,100 @@ SH_COMMON_BUILD_SNIPPET: |
             export CCACHE_DIR="{{ CCACHE_DIR }}"
             {{ CCACHE_EXEC }} --max-size=10G
         fi
-        
-        # extendrom flags
-        export ENABLE_EXTENDROM={{ use_extendrom }}
-        export EXTENDROM_PACKAGES="{{ extendrom_package_list | d(extendrom_package_list_default) }}"
-        export EXTENDROM_FDROID_REPOS="{{ extendrom_fdroid_repos }}"
-        {% if extendrom_packages_skip_dl is defined %}export EXTENDROM_PACKAGES_SKIP_DL={{ extendrom_packages_skip_dl }}{% endif %}
-        export EXTENDROM_PREROOT_BOOT={{ extendrom_preroot_boot }}
-        #export MAGISK_TARGET_ARCH=
-        export EXTENDROM_BOOT_DEBUG={{ extendrom_boot_debug }}
-        export EXTENDROM_DEBUG_PATH={{ extendrom_debug_path |d (extendrom_debug_path_default) }}
-        export EXTENDROM_DEBUG_PATH_SIZE_FULL={{ extendrom_debug_path_size_full | d(extendrom_debug_path_size_full_default) }}
-        export EXTENDROM_DEBUG_PATH_SIZE_KERNEL={{ extendrom_debug_path_size_kernel | d(extendrom_debug_path_size_kernel_default) }}
-        export EXTENDROM_DEBUG_PATH_SIZE_SELINUX={{ extendrom_debug_path_size_selinux | d(extendrom_debug_path_size_selinux_default) }}
-        export EXTENDROM_DEBUG_PATH_SIZE_CRASH={{ extendrom_debug_path_size_crash | d(extendrom_debug_path_size_crash_default) }}
-        export EXTENDROM_SIGNATURE_SPOOFING={{ extendrom_signature_spoofing }}
-        export EXTENDROM_PATCHER_RESET={{ extendrom_patcher_reset }}
-        export EXTENDROM_SIGNING_PATCHES={{ extendrom_signing_patches }}
-        export EXTENDROM_ALLOW_ANY_CALL_RECORDING={{ extendrom_allow_any_call_recording }}
-        # execute extendrom
-        $PWD/vendor/extendrom/er.sh
 
-        echo "[GIT] checking kernel changes in {{ target_kernel_dir }}"
-        # add unstaged changes
-        CMT=0
-        cd {{ target_kernel_dir }}
-        git add -A || CMT=1
-        # check for uncommitted changes
-        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
-        # commit if required
-        if [ $CMT -eq 1 -o $CMTL -gt 0 ];then 
-           git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "uncatched scripted change(s)"
-           echo "[GIT] committed scripted kernel changes for {{ target_kernel_dir }}" >> {{ BUILD_LOG }}
-        fi
-        git status
-        croot
-      
-        # build
-        resetEnv
-        {% if (override_clean_out == "undef" and clean_out == "true") or (override_clean_out == "true") %}
-        mka generate_verity_key
-        {% endif %}
-        {% if axp_build_recovery_only is defined and axp_build_recovery_only %}
-        mka recoveryimage
-        if [ ! -d {{ ZIPDIR }} ]; then mkdir -p {{ ZIPDIR }};fi
-        mv -v out/target/product/{{ target_model }}/recovery.img {{ ZIPDIR }}/{{ axp_recovery_filename }}
-        {% elif custom_build_command is defined %}
-        {{ custom_build_command }}
-        {% elif axp_build_eng | bool %}
-        #mka sepolicy
-        buildDeviceDebug {{ target_model }}
+        # just build bootimage (e.g. for kernel patch tests)
+        {% if build_bootimage_only is defined and build_bootimage_only %}
+            mka bootimage
+            for blame in $(grep error: $LOG | grep -E ':[0-9]+:[0-9]+:'| cut -d / -f19-200 | cut -d : -f1-2 | grep : | sort -u | grep -vE '^$' | tr '\n' " " | sed 's#private/gs-google/##g');do
+                echo "bp=${blame/:*} ln=${blame/*:}"
+                export bp="${blame/:*}" ln="${blame/*:}"
+                export commit=$(git blame $bp |grep "${ln}" | cut -d " " -f1)
+                echo "commit: >$commit<"
+                export subject=$(git log -1 "$commit" | head -n7 | tail -n1 | sed -E 's/^\s+//g')
+                echo "searching applied CVE for.. >${subject}<"
+                if [ ! -z "$subject" ];then
+                    grep "${subject}" $LOG -B1 | cut -d '/' -f2-20 
+                else
+                    echo "ERROR: no subject found"; exit 2
+                fi
+                if [ $? -ne 0 ];then
+                    echo "Cannot find subject in LOG"
+                    exit 3
+                fi
+            done
+            echo "parsing {{ BUILD_LOG }} for troublemaker CVEs finished"
         {% else %}
-        buildDevice {{ target_model }}
+            # extendrom flags
+            export ENABLE_EXTENDROM={{ use_extendrom }}
+            export EXTENDROM_PACKAGES="{{ extendrom_package_list | d(extendrom_package_list_default) }}"
+            export EXTENDROM_FDROID_REPOS="{{ extendrom_fdroid_repos }}"
+            {% if extendrom_packages_skip_dl is defined %}export EXTENDROM_PACKAGES_SKIP_DL={{ extendrom_packages_skip_dl }}{% endif %}
+            export EXTENDROM_PREROOT_BOOT={{ extendrom_preroot_boot }}
+            #export MAGISK_TARGET_ARCH=
+            export EXTENDROM_BOOT_DEBUG={{ extendrom_boot_debug }}
+            export EXTENDROM_DEBUG_PATH={{ extendrom_debug_path |d (extendrom_debug_path_default) }}
+            export EXTENDROM_DEBUG_PATH_SIZE_FULL={{ extendrom_debug_path_size_full | d(extendrom_debug_path_size_full_default) }}
+            export EXTENDROM_DEBUG_PATH_SIZE_KERNEL={{ extendrom_debug_path_size_kernel | d(extendrom_debug_path_size_kernel_default) }}
+            export EXTENDROM_DEBUG_PATH_SIZE_SELINUX={{ extendrom_debug_path_size_selinux | d(extendrom_debug_path_size_selinux_default) }}
+            export EXTENDROM_DEBUG_PATH_SIZE_CRASH={{ extendrom_debug_path_size_crash | d(extendrom_debug_path_size_crash_default) }}
+            export EXTENDROM_SIGNATURE_SPOOFING={{ extendrom_signature_spoofing }}
+            export EXTENDROM_PATCHER_RESET={{ extendrom_patcher_reset }}
+            export EXTENDROM_SIGNING_PATCHES={{ extendrom_signing_patches }}
+            export EXTENDROM_ALLOW_ANY_CALL_RECORDING={{ extendrom_allow_any_call_recording }}
+            # execute extendrom
+            $PWD/vendor/extendrom/er.sh
+    
+            echo "[GIT] checking kernel changes in {{ target_kernel_dir }}"
+            # add unstaged changes
+            CMT=0
+            cd {{ target_kernel_dir }}
+            git add -A || CMT=1
+            # check for uncommitted changes
+            CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
+            # commit if required
+            if [ $CMT -eq 1 -o $CMTL -gt 0 ];then 
+               git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "uncatched scripted change(s)"
+               echo "[GIT] committed scripted kernel changes for {{ target_kernel_dir }}" >> {{ BUILD_LOG }}
+            fi
+            git status
+            croot
+          
+            # build
+            resetEnv
+            {% if (override_clean_out == "undef" and clean_out == "true") or (override_clean_out == "true") %}
+            mka generate_verity_key
+            {% endif %}
+            {% if axp_build_recovery_only is defined and axp_build_recovery_only %}
+            mka recoveryimage
+            if [ ! -d {{ ZIPDIR }} ]; then mkdir -p {{ ZIPDIR }};fi
+            mv -v out/target/product/{{ target_model }}/recovery.img {{ ZIPDIR }}/{{ axp_recovery_filename }}
+            {% elif custom_build_command is defined %}
+            {{ custom_build_command }}
+            {% elif axp_build_eng | bool %}
+            #mka sepolicy
+            buildDeviceDebug {{ target_model }}
+            {% else %}
+            buildDevice {{ target_model }}
+            {% endif %}
+            {% if vbmeta_verify %}
+            # See: https://source.android.com/docs/security/features/verifiedboot/boot-flow 
+            FPID=$(cat user-keys/avb_pkmd.bin | openssl dgst -sha256 | cut -d "=" -f 2 | tr -d " " | tr "[[:lower:]]" "[[:upper:]]")
+            echo -e "\nBOOTLOADER minimal ID"
+            echo -e "\t${FPID:0:8}\n"
+            echo -e "BOOTLOADER full ID:"
+            echo -e "\t${FPID:0:16}"
+            echo -e "\t${FPID:16:16}"
+            echo -e "\t${FPID:32:16}"
+            echo -e "\t${FPID:48:16}\n"
+            out/host/linux-x86/bin/avbtool info_image --image out/target/product/{{ target_model }}/vbmeta.img 2> /dev/null || true
+            out/host/linux-x86/bin/avbtool verify_image --follow_chain_partitions --image out/target/product/{{ target_model }}/vbmeta.img 2> /dev/null \
+                || (out/host/linux-x86/bin/avbtool info_image --image out/target/product/{{ target_model }}/obj/PACKAGING/target_files_intermediates/lineage_{{ target_model }}-target_files-eng.emy/IMAGES/vbmeta.img;\
+                    out/host/linux-x86/bin/avbtool verify_image --follow_chain_partitions --image out/target/product/{{ target_model }}/obj/PACKAGING/target_files_intermediates/lineage_{{ target_model }}-target_files-eng.emy/IMAGES/vbmeta.img)
+            {% endif %}
+    
+            echo -e "\n\nSUCCESS:\nYou should find your build here:\n{{ ZIPDIR }}\n${ZIPINF}"
+            
         {% endif %}
-        {% if vbmeta_verify %}
-        # See: https://source.android.com/docs/security/features/verifiedboot/boot-flow 
-        FPID=$(cat user-keys/avb_pkmd.bin | openssl dgst -sha256 | cut -d "=" -f 2 | tr -d " " | tr "[[:lower:]]" "[[:upper:]]")
-        echo -e "\nBOOTLOADER minimal ID"
-        echo -e "\t${FPID:0:8}\n"
-        echo -e "BOOTLOADER full ID:"
-        echo -e "\t${FPID:0:16}"
-        echo -e "\t${FPID:16:16}"
-        echo -e "\t${FPID:32:16}"
-        echo -e "\t${FPID:48:16}\n"
-        out/host/linux-x86/bin/avbtool info_image --image out/target/product/{{ target_model }}/vbmeta.img 2> /dev/null || true
-        out/host/linux-x86/bin/avbtool verify_image --follow_chain_partitions --image out/target/product/{{ target_model }}/vbmeta.img 2> /dev/null \
-            || (out/host/linux-x86/bin/avbtool info_image --image out/target/product/{{ target_model }}/obj/PACKAGING/target_files_intermediates/lineage_{{ target_model }}-target_files-eng.emy/IMAGES/vbmeta.img;\
-                out/host/linux-x86/bin/avbtool verify_image --follow_chain_partitions --image out/target/product/{{ target_model }}/obj/PACKAGING/target_files_intermediates/lineage_{{ target_model }}-target_files-eng.emy/IMAGES/vbmeta.img)
-        {% endif %}
-
-        echo -e "\n\nSUCCESS:\nYou should find your build here:\n{{ ZIPDIR }}\n${ZIPINF}"
 
 # we patch the kernel!
 sec_patch_level: '05'
