axp: - allow detecting cve error blames when running kleaf - lint fixes - testing new cve exclude approach using ansible templates

diff --git a/roles/axp/common/defaults/main.yml b/roles/axp/common/defaults/main.yml
--- a/roles/axp/common/defaults/main.yml
+++ b/roles/axp/common/defaults/main.yml
@@ -13,9 +13,9 @@ git_repo_main_manifests: "https://github.com/LineageOS/android.git"
 # the organization name within git(ea):
 git_axpos_org_name: "AXP.OS"
 # always push changes for reproducible builds
-commit_push: True
+commit_push: true
 # just push changes after patching, skip build
-just_git_push: False
+just_git_push: false
 
 # codeberg
 # tea login add --name NNNN --ssh-key XXXXX --url https://codeberg.org --token XXXXX
@@ -524,10 +524,25 @@ SH_COMMON_BUILD_SNIPPET: |
 
     ########################### BUILD #########################
 
+    f_detect_kerr(){
+        set +e
+        resetEnv
+        vendor/axp/scripts/find_cve_error.sh --parse -k {{ target_kernel_dir }} -L {{ BUILD_LOG }}
+        just_cve_excl=$(grep "PROBLEMATIC_CVES:" {{ BUILD_LOG }} | cut -d ':' -f2- | tr '\n' ' ')
+
+        if [ -n "$just_cve_excl" ];then
+            echo -e "\ndirty test: revert CVE's and re-test like:"
+            echo -e "\tcd {{ target_kernel_dir }} && for p in $just_cve_excl; do patch -p1 -R < \$DOS_PATCHES_LINUX_CVES/\$p;done; croot; time ~/build_{{ sub_model | d(target_model) }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh | tee ~/LOG"
+            echo -e "\nIf you then encounter another error do:\n\tcat ~/LOG >> {{ BUILD_LOG }}"
+            echo -e "\tvendor/axp/scripts/find_cve_error.sh --parse -k {{ target_kernel_dir }} -L {{ BUILD_LOG }}"
+        fi
+        exit 5
+    }
+
     {% if pixel_kernel_gki %}
     ###### BUILD GOOGLE PIXEL KERNEL (KLEAF)
     cd {{ git_pixel_kernel_dir }}
-    {{ pixel_kernel_buildcmd | d('echo "Error: missing pixel_kernel_buildcmd def"; false') }} >> {{ BUILD_LOG }} 2>&1
+    {{ pixel_kernel_buildcmd | d('echo "Error: missing pixel_kernel_buildcmd def"; false') }} >> {{ BUILD_LOG }} 2>&1 || f_detect_kerr
     KERN_REL_DIR=$(grep string_value {{ SRCPATH }}/build/release/flag_values/{{ android_target_release }}/RELEASE_KERNEL_{{ target_model | upper() }}_DIR.textproto | cut -d '"' -f2 | tr -d " " | tail -n1)
     echo "KERN_REL_DIR: >{{ SRCPATH }}/$KERN_REL_DIR<" >> {{ BUILD_LOG }}
     if [ -d "{{ SRCPATH }}/$KERN_REL_DIR" ];then
@@ -566,21 +581,6 @@ SH_COMMON_BUILD_SNIPPET: |
         export CCACHE_DIR="{{ CCACHE_DIR }}"
         {{ CCACHE_EXEC }} --max-size={{ ccache_max_size }}
     fi
-
-    f_detect_kerr(){
-        set +e
-        resetEnv
-        vendor/axp/scripts/find_cve_error.sh --parse -k {{ target_kernel_dir }} -L {{ BUILD_LOG }}
-        just_cve_excl=$(grep "PROBLEMATIC_CVES:" {{ BUILD_LOG }} | cut -d ':' -f2- | tr '\n' ' ')
-
-        if [ -n "$just_cve_excl" ];then
-            echo -e "\ndirty test: revert CVE's and re-test like:"
-            echo -e "\tcd {{ target_kernel_dir }} && for p in $just_cve_excl; do patch -p1 -R < \$DOS_PATCHES_LINUX_CVES/\$p;done; croot; time ~/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh | tee ~/LOG"
-            echo -e "\nIf you then encounter another error do:\n\tcat ~/LOG >> {{ BUILD_LOG }}"
-            echo -e "\tvendor/axp/scripts/find_cve_error.sh --parse -k {{ target_kernel_dir }} -L {{ BUILD_LOG }}"
-        fi
-        exit 5
-    }
 
     {% if build_bootimage_only is defined and build_bootimage_only %}
         # just build bootimage (e.g. for kernel patch tests)
