Update main.yml

diff --git a/roles/axp/common/defaults/main.yml b/roles/axp/common/defaults/main.yml
--- a/roles/axp/common/defaults/main.yml
+++ b/roles/axp/common/defaults/main.yml
@@ -312,7 +312,10 @@ SH_COMMON_BUILD_SNIPPET: |
         # just build bootimage (e.g. for kernel patch tests)
         {% if build_bootimage_only is defined and build_bootimage_only %}
             mka bootimage
-            for blame in $(grep error: $LOG | grep -E ':[0-9]+:[0-9]+:'| cut -d / -f19-200 | cut -d : -f1-2 | grep : | sort -u | grep -vE '^$' | tr '\n' " " | sed 's#private/gs-google/##g');do
+            echo "building bootimage ended with: $?"
+
+            cd {{ target_kernel_dir }}
+            for blame in $(grep error: {{ BUILD_LOG }} | grep -E ':[0-9]+:[0-9]+:'| cut -d / -f19-200 | cut -d : -f1-2 | grep : | sort -u | grep -vE '^$' | tr '\n' " " | sed 's#private/gs-google/##g');do
                 echo "bp=${blame/:*} ln=${blame/*:}"
                 export bp="${blame/:*}" ln="${blame/*:}"
                 export commit=$(git blame $bp |grep "${ln}" | cut -d " " -f1)
@@ -320,12 +323,12 @@ SH_COMMON_BUILD_SNIPPET: |
                 export subject=$(git log -1 "$commit" | head -n7 | tail -n1 | sed -E 's/^\s+//g')
                 echo "searching applied CVE for.. >${subject}<"
                 if [ ! -z "$subject" ];then
-                    grep "${subject}" $LOG -B1 | cut -d '/' -f2-20 
+                    grep "${subject}" {{ BUILD_LOG }} -B1 | cut -d '/' -f2-20 
                 else
                     echo "ERROR: no subject found"; exit 2
                 fi
                 if [ $? -ne 0 ];then
-                    echo "Cannot find subject in LOG"
+                    echo "Cannot find subject in LOG! not a CVE??!"
                     exit 3
                 fi
             done
