Update main.yml

diff --git a/roles/graphene/common/defaults/main.yml b/roles/graphene/common/defaults/main.yml
--- a/roles/graphene/common/defaults/main.yml
+++ b/roles/graphene/common/defaults/main.yml
@@ -30,3 +30,28 @@ cdtree_cl: |-
 dl_links: |-
   ***Download:*** [{{ ROMFILE.stdout | replace("-","\-") | replace("_","\_") | replace(".","\.") }} ]({{ leech_server }}/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }})
 
+# common snippets for templates
+
+SH_GRAPHENE_GPG: |
+       # list of keyservers for importing gpg pub keys
+       # space separated
+       GPG_KEYSERVER="keyserver.ubuntu.com keys.openpgp.org pgp.mit.edu"
+
+       # gpg keys to import space separated
+       # stinger:  65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
+       GPG_KEYS="65EEFE022108E2B708CBFCF7F9E712E59AF5F22A"
+
+       F_GET_GPG_KEYS(){
+           # import all required gpg pub keys
+           for k in $GPG_KEYS;do
+              if [ $GPG_FORCE_DL -eq 0 ];then
+                  gpg -k $k 2>&1 >> /dev/null && echo "[$FUNCNAME] ... skipping already imported gpg pub key ($k)" && continue
+              fi
+              for s in $GPG_KEYSERVER;do
+                  echo "- trying $k from $s"
+                  gpg --keyserver $s --recv-key $k >> /dev/null 2>&1 && echo "[$FUNCNAME] ... imported gpg key $k from $s" && continue 2
+              done
+              echo "[$FUNCNAME] ERROR: Cannot download a required gpg pub key: $k"
+              exit 3
+           done
+       }
