secpatch: trying to fix dep chains

diff --git a/roles/common/tasks/secpatch.yml b/roles/common/tasks/secpatch.yml
--- a/roles/common/tasks/secpatch.yml
+++ b/roles/common/tasks/secpatch.yml
@@ -80,13 +80,20 @@
       ansible.builtin.file:
           path: "{{ SRCPATH }}/CHERRYPICK.FAILED"
           state: absent
-    
-    - name: "SECURITY PATCH MERGE: apply security patches in ASB order"
+
+    - name: SECURITY PATCH MERGE: apply security patches in ASB order
+      vars:
+        cherry_replaced: >-
+          {% set result = cherry %}
+          {% for dep in secpatch_static_dependencies | default([]) %}
+          {%   set result = result | regex_replace(dep.id ~ '\\b', dep.dep) %}
+          {% endfor %}
+          {{ result }}
       ansible.builtin.shell: |
-        if [ -f CHERRYPICK.FAILED ];then echo "Previous cherry-picked failed!! Skipping...."; exit 3;fi
+        if [ -f CHERRYPICK.FAILED ]; then echo "Previous cherry-picked failed!! Skipping...."; exit 3; fi
         source build/envsetup.sh > /dev/null
-        echo "patching ASB : {{ cherry | regex_replace('-f ',' ') }}"
-        {{ cherry | regex_replace('-f ',' ') | regex_replace('external/dng/sdk','external/dng_sdk') }} -v >> {{ BUILD_LOG }} 2>&1 || {{ cherry }} -fv >> {{ BUILD_LOG }} || (touch CHERRYPICK.FAILED ;exit 123)
+        echo "patching ASB : {{ cherry_replaced | ansible.builtin.regex_replace('-f ',' ') }}"
+        {{ cherry_replaced | regex_replace('-f ',' ') | regex_replace('external/dng/sdk','external/dng_sdk') }} -v >> {{ BUILD_LOG }} 2>&1 || {{ cherry_replaced }} -fv >> {{ BUILD_LOG }} || (touch CHERRYPICK.FAILED ;exit 123)
       args:
         executable: /bin/bash
         chdir: "{{ SRCPATH }}"
