common+axp:  fix secpatch handling

diff --git a/roles/common/tasks/secpatch.yml b/roles/common/tasks/secpatch.yml
--- a/roles/common/tasks/secpatch.yml
+++ b/roles/common/tasks/secpatch.yml
@@ -47,7 +47,7 @@
 - name: "Flatten sec_patch_topics"
   ansible.builtin.set_fact:
     flattened_sec_patch_topics: "{{ sec_patch_topics | flatten }}"
- 
+
 - name: "Define Queries by ASB"
   ansible.builtin.set_fact:
     pick_queries: >-
@@ -57,7 +57,7 @@
   loop: "{{ flattened_sec_patch_topics }}"
   
 - block:
-   
+
     - name: "SECURITY PATCH MERGE: create repopick lists by year (required to find path names)"
       # "yes y | " at the beginng is required to auto-continue when the changes are > 200
       ansible.builtin.shell: >
@@ -85,41 +85,47 @@
 
     - name: "SECURITY PATCH MERGE: apply security patches in ASB order"
       ansible.builtin.shell: |
-        if [ -f CHERRYPICK.FAILED ]; then echo "Previous cherry-picked failed!! Skipping...."; exit 3; fi
+        if [ -f CHERRYPICK.FAILED ]; then echo "Previous cherry-picked failed!! Skipping...." >> {{ BUILD_LOG }}; exit 3; fi
         unset id order batch
         cmd="{{ cherry | regex_replace('-f ',' ') | regex_replace('external/dng/sdk','external/dng_sdk') }}"
-        
+
         # set static order if required
         for batch in {{ secpatch_static_dependencies }};do
           id="${batch/:*}"
           chk=$(echo "$cmd" | grep -c "$id")
           if [ $chk -gt 0 ];then
             deps=$(echo "${batch/*:}" | tr ',' ' ')
-            
             for cl in $deps;do
               cmd=$(echo "$cmd" | sed "s/$cl//g")
             done
-            
             cmd=$(echo "$cmd" | sed "s/$id/$deps $id/g")
-            echo "FORCED NEW PATCH ORDER for: $id ($deps $id)"
+            echo "FORCED NEW PATCH ORDER for: $id ($deps $id)" >> {{ BUILD_LOG }}
           fi
         done
         
         source build/envsetup.sh > /dev/null
-        echo -e "patching ASB:\n$cmd"
+        echo -e "patching ASB:\n$cmd" >> {{ BUILD_LOG }}
         
         $cmd -v >> {{ BUILD_LOG }} 2>&1 || $cmd -fv >> {{ BUILD_LOG }} || (touch CHERRYPICK.FAILED ;exit 123)
       args:
         executable: /bin/bash
         chdir: "{{ SRCPATH }}"
       register: spres
-      loop: "{{ picklist.results | selectattr('changed', 'eq', True) 
-               | sort(attribute='item.key') 
-               | map(attribute='stdout_lines') 
-               | flatten }}"
+      loop: "{{ picklist.results | selectattr('changed', 'eq', True)
+                | sort(attribute='item.key')
+                | map(attribute='stdout_lines')
+                | flatten }}"
       when: picklist.changed
       loop_control:
         loop_var: cherry
+
+    - name: "SECURITY PATCH MERGE: update manifest"
+      ansible.builtin.copy:
+        src: "{{ SRCPATH }}/android/default.xml"
+        dest: "{{ SRCPATH }}/.repo/manifests/default.xml"
+
+    - name: "SECURITY PATCH MERGE: re-sync (to grab new forks)!"
+      ansible.builtin.include_tasks: ../../../common/tasks/sync.yml
     
   rescue:
     - name: "Fail fast on failures" # fail immediately and not waiting for finishing full loops
@@ -158,9 +164,9 @@
           {{ DOS_INIT |d('export AXP_GIT_AUTHOR="$USER" AXP_GIT_MAIL="$USER_MAIL"') }}
 
           {% if android_version_int | int > 13 %}
-                cd build/release
+          cd build/release
           {% else %}
-                cd build/core
+          cd build/core
           {% endif %}
           
           CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
