axp: g4: add arb blob check

diff --git a/roles/axp/g4/templates/build.sh.j2 b/roles/axp/g4/templates/build.sh.j2
--- a/roles/axp/g4/templates/build.sh.j2
+++ b/roles/axp/g4/templates/build.sh.j2
@@ -1,1 +1,20 @@
 {{ SH_COMMON_BUILD_SNIPPET | replace('g4',sub_model) }}
+
+# check correct blobs from unified device tree
+cd {{ SRCPATH }}
+
+rm /tmp/*_venuscheck.md5 || echo "no previous venus md5 found"
+case {{ sub_model }} in
+	h815|h815_usu|f500_usu|h819_usu)
+    	echo "d1f6fe863643b1e8d1e597762474928c out/target/product/{{ sub_model }}/system/etc/firmware/venus.mbn" > /tmp/{{ sub_model }}_venuscheck.md5
+    	md5sum -c /tmp/{{ sub_model }}_venuscheck.md5
+    ;;
+    h810_usu|h811|h812_usu|ls991_usu|us991_usu|vs986_usu)
+    	echo "78e5cf520d0de4a413ef1cfa7bbbe713 out/target/product/{{ sub_model }}/system/etc/firmware/venus.mbn" > /tmp/{{ sub_model }}_venuscheck.md5
+        md5sum -c /tmp/{{ sub_model }}_venuscheck.md5
+    ;;
+    *)
+    echo "FAILED TO VERIFY VENUS MD5 FOR {{ sub_model }}!! NO VALID MODEL FOUND FOR COMPARISON"
+    exit 99
+    ;;
+esac
